//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Nhi.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createByID { get; set; }
        public string modifiedByID { get; set; }
        public Nullable<System.DateTime> modifiedByDate { get; set; }
        public string detail { get; set; }
        public string metatTitle { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
