//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Nhi.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string link { get; set; }
        public string taget { get; set; }
        public Nullable<int> dislayOrder { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual MenuType MenuType { get; set; }
    }
}
