//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Nhi.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long ID { get; set; }
        public string fullName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateSet { get; set; }
        public string message { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<int> payID { get; set; }
        public bool status { get; set; }
    
        public virtual Pay Pay { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
