//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Nhi.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long ID { get; set; }
        public string code { get; set; }
        public string productName { get; set; }
        public string image { get; set; }
        public string moreImages { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> promotionPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public string chatlieu { get; set; }
        public string madeIn { get; set; }
        public string size { get; set; }
        public Nullable<int> like { get; set; }
        public Nullable<int> viewCount { get; set; }
        public Nullable<long> categoryID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createByID { get; set; }
        public string modifiedByID { get; set; }
        public Nullable<System.DateTime> modifiedByDate { get; set; }
        public string detail { get; set; }
        public string description { get; set; }
        public string metatTitle { get; set; }
        public string metaKeywords { get; set; }
        public string metaDescription { get; set; }
        public bool status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
