//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Nhi.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public Nullable<int> roleID { get; set; }
        public bool status { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
